### ISSUE TITLE
html5 semantic tags

### ISSUE THREAD

**Issue by rimmesbe** [bobhoward118/prj-rev-bwfs-dasmoto#1]
This would be a good spot for a `<header>` tag instead of div, more semantic. html5 semantic tags are a hot topic right now.

https://github.com/bobhoward118/prj-rev-bwfs-dasmoto/blob/master/j-REVIEWDasmotosArtsAndCrafts/index.html#L10

**Comment by bobhoward118** [comment]
Changed header class to header tag in html & css files
