### ISSUE TITLE
sections and labeling

### ISSUE THREAD

**Issue by rimmesbe** [bobhoward118/prj-rev-bwfs-dasmoto#2]
This might be a good spot for `<section>` tag. I would also consider giving the 'brushes' class to the div instead of the h2, so that we know immediately which section is which. Then you could do .brushes h2 { } or another class for the background color: .skyblue-bg {background: skyblue;}

https://github.com/bobhoward118/prj-rev-bwfs-dasmoto/blob/master/j-REVIEWDasmotosArtsAndCrafts/index.html#L14

**Comment by bobhoward118** [comment]
Added <section>, moved h2 classes to divs, did not add h2 color classes (skyblue-bg) since they are not repeated.
