### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by rimmesbe** [bobhoward118/prj-rev-bwfs-dasmoto#5]
Grade: Satisfactory

Summary: Really good job on this project, your code was very organized and well thought out. I made a couple comments about little tweaks you should consider moving forward. I would maybe do a little reading on CSS naming conventions (there are a bunch of different ones) and start using a bit more descriptive class names. Here is a link to BEM conventions that also has links to other styles: http://getbem.com/introduction/

**Comment by bobhoward118** [comment]
I reworked every class to confirm to BEM naming convention.
